
spring:
  application:
    name: ProyectoFinal

  datasource:
    url:           jdbc:mysql://localhost:3306/empresa_muebles
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:  root
    password: '961508'

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

    implicit-naming-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl