spring:
  application:
    name: ProyectoFinal

  datasource:
    url:      jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL              # jdbc:mysql://localhost:3306/empresa_muebles
    driver-class-name: org.h2.Driver #com.mysql.cj.jdbc.Driver
    username:  sa #root
    password: # '961508'

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect #org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto:  update # validate

    implicit-naming-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl